
package client1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @return
     *     returns java.util.List<client1.Table>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateTables", targetNamespace = "http://services/", className = "client1.GenerateTables")
    @ResponseWrapper(localName = "generateTablesResponse", targetNamespace = "http://services/", className = "client1.GenerateTablesResponse")
    @Action(input = "http://services/ReservationService/generateTablesRequest", output = "http://services/ReservationService/generateTablesResponse")
    public List<Table> generateTables();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client1.Reservation
     */
    @WebMethod(operationName = "ReserveTable")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReserveTable", targetNamespace = "http://services/", className = "client1.ReserveTable")
    @ResponseWrapper(localName = "ReserveTableResponse", targetNamespace = "http://services/", className = "client1.ReserveTableResponse")
    @Action(input = "http://services/ReservationService/ReserveTableRequest", output = "http://services/ReservationService/ReserveTableResponse")
    public Reservation reserveTable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
