
package client2;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckPaymentService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckPaymentService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<client2.ConfirmPaymentResponse>
     */
    @WebMethod(operationName = "ConfirmPayment")
    @RequestWrapper(localName = "ConfirmPayment", targetNamespace = "http://services/", className = "client2.ConfirmPayment")
    @ResponseWrapper(localName = "ConfirmPaymentResponse", targetNamespace = "http://services/", className = "client2.ConfirmPaymentResponse")
    public Response<ConfirmPaymentResponse> confirmPaymentAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ConfirmPayment")
    @RequestWrapper(localName = "ConfirmPayment", targetNamespace = "http://services/", className = "client2.ConfirmPayment")
    @ResponseWrapper(localName = "ConfirmPaymentResponse", targetNamespace = "http://services/", className = "client2.ConfirmPaymentResponse")
    public Future<?> confirmPaymentAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ConfirmPaymentResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client2.Prepayment
     */
    @WebMethod(operationName = "ConfirmPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConfirmPayment", targetNamespace = "http://services/", className = "client2.ConfirmPayment")
    @ResponseWrapper(localName = "ConfirmPaymentResponse", targetNamespace = "http://services/", className = "client2.ConfirmPaymentResponse")
    @Action(input = "http://services/CheckPaymentService/ConfirmPaymentRequest", output = "http://services/CheckPaymentService/ConfirmPaymentResponse")
    public Prepayment confirmPayment(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

}
