
package client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckPayment", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8082/Check?wsdl")
public class CheckPayment
    extends Service
{

    private final static URL CHECKPAYMENT_WSDL_LOCATION;
    private final static WebServiceException CHECKPAYMENT_EXCEPTION;
    private final static QName CHECKPAYMENT_QNAME = new QName("http://services/", "CheckPayment");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/Check?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKPAYMENT_WSDL_LOCATION = url;
        CHECKPAYMENT_EXCEPTION = e;
    }

    public CheckPayment() {
        super(__getWsdlLocation(), CHECKPAYMENT_QNAME);
    }

    public CheckPayment(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKPAYMENT_QNAME, features);
    }

    public CheckPayment(URL wsdlLocation) {
        super(wsdlLocation, CHECKPAYMENT_QNAME);
    }

    public CheckPayment(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKPAYMENT_QNAME, features);
    }

    public CheckPayment(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckPayment(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckPaymentService
     */
    @WebEndpoint(name = "CheckPaymentPort")
    public CheckPaymentService getCheckPaymentPort() {
        return super.getPort(new QName("http://services/", "CheckPaymentPort"), CheckPaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckPaymentService
     */
    @WebEndpoint(name = "CheckPaymentPort")
    public CheckPaymentService getCheckPaymentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "CheckPaymentPort"), CheckPaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKPAYMENT_EXCEPTION!= null) {
            throw CHECKPAYMENT_EXCEPTION;
        }
        return CHECKPAYMENT_WSDL_LOCATION;
    }

}
